# Generated by Django 6.0.3 on 2026-05-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0005_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=20),
        ),
    ]
